<?php

namespace UpdatedData\AnonFiles;

enum ApiError: int
{
    case ERROR_FILE_NOT_PROVIDED = 10;
    case ERROR_FILE_EMPTY = 11;
    case ERROR_FILE_INVALID = 12;
    case ERROR_USER_MAX_FILES_PER_HOUR_REACHED = 20;
    case ERROR_USER_MAX_FILES_PER_DAY_REACHED = 21;
    case ERROR_USER_MAX_BYTES_PER_HOUR_REACHED = 22;
    case ERROR_USER_MAX_BYTES_PER_DAY_REACHED = 23;
    case ERROR_FILE_DISALLOWED_TYPE = 30;
    case ERROR_FILE_SIZE_EXCEEDED = 31;
    case ERROR_FILE_BANNED = 32;
    case STATUS_ERROR_SYSTEM_FAILURE = 40;
    case ERROR_FILE_NOT_FOUND = 404;
}